In [1]:
import numpy as np

### DatatTypes & Attributes 

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
               [7, 8, 9]],
              
                [[10, 11, 12],
               [13, 14, 15],
                [16, 17, 18]]])

In [5]:
a1.shape

(3,)

In [6]:
a2.shape

(2, 3)

In [7]:
a3.shape

(2, 3, 3)

In [8]:
a1

array([1, 2, 3])

In [9]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [13]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)

In [16]:
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

   ## Creating Arrays

In [17]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [18]:
sample_array.dtype

dtype('int32')

In [19]:
ones = np.ones((2, 3))

In [20]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
ones.dtype

dtype('float64')

In [22]:
type(ones)

numpy.ndarray

In [23]:
zeros = np.zeros((2, 3))

In [24]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [26]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[5, 2, 5, 0, 4],
       [9, 5, 3, 4, 5],
       [2, 5, 8, 7, 2]])

In [27]:
random_array.size

15

In [28]:
random_array.shape

(3, 5)

In [29]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.31218295, 0.17204582, 0.57234809],
       [0.22065911, 0.05609063, 0.08626203],
       [0.50737085, 0.79707043, 0.55174933],
       [0.34553125, 0.39063699, 0.36601092],
       [0.1654749 , 0.36448957, 0.37917178]])

In [30]:
random_array_2.shape

(5, 3)

In [31]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.02374844, 0.68512019, 0.66232231],
       [0.35390832, 0.89353255, 0.50366503],
       [0.53147817, 0.76087105, 0.36745904],
       [0.91786718, 0.88728208, 0.94691489],
       [0.79137605, 0.32506844, 0.04282711]])

In [32]:
# Pseudo_random numbers
seed = np.random.seed(seed=99999)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [33]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [34]:
random_array_4.shape

(5, 3)

##  3.Viewing Arrays and Matrices

In [38]:
np.unique(random_array_4)

array([0, 1, 3, 4, 5, 6, 8, 9])

In [39]:
a1

array([1, 2, 3])

In [40]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [41]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [42]:
a1[0]

1

In [43]:
a2[0]

array([1. , 2. , 3.3])

In [45]:
a3.shape

(2, 3, 3)

In [46]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [48]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [49]:
a2[1]

array([4. , 5. , 6.5])

In [50]:
a3[:2, :2, :2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [51]:
a4 = np.random.randint(10, size=(2, 3, 4, 5))
a4

array([[[[3, 5, 8, 8, 7],
         [5, 0, 0, 2, 8],
         [9, 6, 4, 9, 7],
         [3, 3, 8, 3, 0]],

        [[1, 0, 0, 6, 7],
         [7, 9, 3, 0, 7],
         [7, 7, 0, 5, 4],
         [3, 1, 3, 1, 3]],

        [[4, 3, 1, 9, 5],
         [9, 1, 2, 3, 2],
         [2, 5, 7, 3, 0],
         [9, 9, 3, 4, 5]]],


       [[[3, 0, 4, 8, 6],
         [7, 2, 7, 3, 8],
         [6, 6, 5, 6, 5],
         [7, 1, 5, 4, 4]],

        [[9, 9, 0, 6, 2],
         [6, 8, 2, 4, 1],
         [6, 1, 5, 1, 6],
         [9, 8, 6, 5, 9]],

        [[7, 5, 4, 9, 6],
         [8, 1, 5, 5, 8],
         [3, 7, 7, 9, 4],
         [7, 5, 9, 6, 2]]]])

In [54]:
a4.shape, a4.ndim

((2, 3, 4, 5), 4)

In [57]:
# Get the first 4 numbers of the inner most arrays
a4[:, :, :, :4]


array([[[[3, 5, 8, 8],
         [5, 0, 0, 2],
         [9, 6, 4, 9],
         [3, 3, 8, 3]],

        [[1, 0, 0, 6],
         [7, 9, 3, 0],
         [7, 7, 0, 5],
         [3, 1, 3, 1]],

        [[4, 3, 1, 9],
         [9, 1, 2, 3],
         [2, 5, 7, 3],
         [9, 9, 3, 4]]],


       [[[3, 0, 4, 8],
         [7, 2, 7, 3],
         [6, 6, 5, 6],
         [7, 1, 5, 4]],

        [[9, 9, 0, 6],
         [6, 8, 2, 4],
         [6, 1, 5, 1],
         [9, 8, 6, 5]],

        [[7, 5, 4, 9],
         [8, 1, 5, 5],
         [3, 7, 7, 9],
         [7, 5, 9, 6]]]])

## 