In [1]:
import numpy as np

### DatatTypes & Attributes 

In [2]:
# NumPy's main datatype is ndarray
a1 = np.array([1, 2, 3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2 = np.array([[1, 2.0, 3.3],
               [4, 5, 6.5]])

a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
               [7, 8, 9]],
              
                [[10, 11, 12],
               [13, 14, 15],
                [16, 17, 18]]])

In [5]:
a1.shape

(3,)

In [6]:
a2.shape

(2, 3)

In [7]:
a3.shape

(2, 3, 3)

In [8]:
a1

array([1, 2, 3])

In [9]:
a2

array([[1. , 2. , 3.3],
       [4. , 5. , 6.5]])

In [10]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [11]:
a1.ndim, a2.ndim, a3.ndim

(1, 2, 3)

In [12]:
a1.dtype, a2.dtype, a3.dtype

(dtype('int32'), dtype('float64'), dtype('int32'))

In [13]:
a1.size, a2.size, a3.size

(3, 6, 18)

In [14]:
type(a1), type(a2), type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [15]:
# Create a DataFrame from a NumPy array
import pandas as pd

df = pd.DataFrame(a2)

In [16]:
df

0    1    2
0  1.0  2.0  3.3
1  4.0  5.0  6.5

   ## Creating Arrays

In [17]:
sample_array = np.array([1,2,3])
sample_array

array([1, 2, 3])

In [18]:
sample_array.dtype

dtype('int32')

In [19]:
ones = np.ones((2, 3))

In [20]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [21]:
ones.dtype

dtype('float64')

In [22]:
type(ones)

numpy.ndarray

In [23]:
zeros = np.zeros((2, 3))

In [24]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [25]:
range_array = np.arange(0, 10, 2)
range_array

array([0, 2, 4, 6, 8])

In [26]:
random_array = np.random.randint(0, 10, size=(3, 5))
random_array

array([[4, 5, 6, 8, 7],
       [0, 0, 3, 3, 7],
       [2, 8, 4, 4, 3]])

In [27]:
random_array.size

15

In [28]:
random_array.shape

(3, 5)

In [29]:
random_array_2 = np.random.random((5, 3))
random_array_2

array([[0.86842884, 0.2224223 , 0.89336536],
       [0.22109662, 0.80101165, 0.36955771],
       [0.64582229, 0.70751738, 0.77476193],
       [0.43192085, 0.61250501, 0.27108235],
       [0.15722647, 0.5429736 , 0.37980974]])

In [30]:
random_array_2.shape

(5, 3)

In [31]:
random_array_3 = np.random.rand(5, 3)
random_array_3

array([[0.37034375, 0.63071868, 0.49189869],
       [0.27344135, 0.97892868, 0.87243495],
       [0.48837766, 0.21020502, 0.9568118 ],
       [0.47355995, 0.39049073, 0.55835405],
       [0.19174834, 0.13899125, 0.06212242]])

In [57]:
# Pseudo_random numbers
seed = np.random.seed(seed=99999)
random_array_4 = np.random.randint(10, size=(5,3))
random_array_4

array([[0, 3, 1],
       [8, 1, 3],
       [8, 5, 6],
       [0, 6, 0],
       [4, 0, 9]])

In [67]:
np.random.seed(7)
random_array_5 = np.random.random((5, 3))
random_array_5

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [51]:
random_array_4.shape

(5, 3)