# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np


In [2]:
# Create a 1-dimensional NumPy array using np.array()
a1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
a2 = np.array([[1, 2, 3 ],[4, 5, 6] ])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]],
               [[10, 11, 12], 
                [13, 14, 15],
                [16, 17, 18]]])   
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [3]:
# Attributes of 1-dimensional narray (shape, 
# number of dimensions, data type, size and type)
a1.ndim , a1.dtype, a1.size, type(a1)

(1, dtype('int32'), 3, numpy.ndarray)

In [4]:
# Attributes of 2-dimensional array
a2.ndim, a2.dtype, a2.size, type(a2)

(2, dtype('int32'), 6, numpy.ndarray)

In [5]:
# Attributes of 3-dimensional array
a3.ndim, a3.dtype, a3.size, type(a3) 

(3, dtype('int32'), 18, numpy.ndarray)

In [7]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd

df = pd.DataFrame(a2)
df

0  1  2
0  1  2  3
1  4  5  6

In [9]:
# Create an array of shape (10, 2) with only ones
ones = np.ones((10,2))
ones


array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [10]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros((7, 2, 3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [13]:
# Create an array within a range of 0 and 100 with step 3
range_array = np.arange(0, 100, 3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [14]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
random_array = np.random.randint(0, 10, (7, 2))
random_array

array([[0, 2],
       [0, 6],
       [2, 2],
       [7, 2],
       [6, 2],
       [6, 6],
       [1, 8]])

In [15]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array2 = np.random.random((3, 5))
random_array2


array([[0.97169889, 0.47509086, 0.87610872, 0.76160208, 0.51839016],
       [0.82441604, 0.93219164, 0.15934382, 0.13699464, 0.042707  ],
       [0.19713582, 0.57467801, 0.59501262, 0.40984354, 0.59153032]])

In [27]:
# Set the random seed to 42
seed = np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array3 = np.random.randint(0, 10, (4, 6))
random_array3

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [28]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
random_array4 = np.random.randint(1, 10, (3, 7))
print(random_array4)
# Find the unique numbers in the array you just created
np.unique(random_array4)

[[9 1 3 7 4 9 3]
 [5 3 7 5 9 7 2]
 [4 9 2 9 5 2 4]]


array([1, 2, 3, 4, 5, 7, 9])

In [29]:
# Find the 0'th index of the latest array you created
random_array4[0]

array([9, 1, 3, 7, 4, 9, 3])

In [30]:
# Get the first 2 rows of latest array you created
random_array4[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [33]:
# Get the first 2 values of the first 2 rows of the latest array
random_array4[:2, :2]

array([[9, 1],
       [5, 3]])

In [35]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variablesn
random_array5 = np.random.randint(0, 10, (3, 5))
print(random_array5)
new_ones = np.ones((3,5))
new_ones

[[9 1 9 3 7]
 [6 8 7 4 1]
 [4 7 9 8 8]]


array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [36]:
# Add the two arrays together
random_array5 + new_ones

array([[10.,  2., 10.,  4.,  8.],
       [ 7.,  9.,  8.,  5.,  2.],
       [ 5.,  8., 10.,  9.,  9.]])

In [37]:
# Create another array of ones of shape (5, 3)
another_ones = np.ones((5, 3))
another_ones

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [38]:
# Try add the array of ones and the other most recent array together
new_ones + another_ones

ValueError: operands could not be broadcast together with shapes (3,5) (5,3) 

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [40]:
# Create another array of ones of shape (3, 5)
t_ones = another_ones.T
t_ones

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [41]:
# Subtract the new array of ones from the other most recent array
random_array5 - t_ones

array([[8., 0., 8., 2., 6.],
       [5., 7., 6., 3., 0.],
       [3., 6., 8., 7., 7.]])

In [42]:
# Multiply the ones array with the latest array
t_ones * random_array5

array([[9., 1., 9., 3., 7.],
       [6., 8., 7., 4., 1.],
       [4., 7., 9., 8., 8.]])

In [43]:
# Take the latest array to the power of 2 using '**'
random_array5 ** 2

array([[81,  1, 81,  9, 49],
       [36, 64, 49, 16,  1],
       [16, 49, 81, 64, 64]])

In [44]:
# Do the same thing with np.square()
np.square(random_array5)

array([[81,  1, 81,  9, 49],
       [36, 64, 49, 16,  1],
       [16, 49, 81, 64, 64]])

In [45]:
# Find the mean of the latest array using np.mean()
np.mean(random_array5)

6.066666666666666

In [47]:
# Find the maximum of the latest array using np.max()
print(random_array5)
np.max(random_array5)

[[9 1 9 3 7]
 [6 8 7 4 1]
 [4 7 9 8 8]]


9

In [48]:
# Find the minimum of the latest array using np.min()
np.min(random_array5)

1

In [49]:
# Find the standard deviation of the latest array
np.std(random_array5)


2.6948510575210314

In [50]:
# Find the variance of the latest array
np.var(random_array5)

7.262222222222222

In [52]:
# Reshape the latest array to (3, 5, 1)
reshaped_array = random_array5.reshape((3, 5, 1))
reshaped_array

array([[[9],
        [1],
        [9],
        [3],
        [7]],

       [[6],
        [8],
        [7],
        [4],
        [1]],

       [[4],
        [7],
        [9],
        [8],
        [8]]])

In [53]:
# Transpose the latest array
reshaped_array.T

array([[[9, 6, 4],
        [1, 8, 7],
        [9, 7, 9],
        [3, 4, 8],
        [7, 1, 8]]])

What does the transpose do?

In [62]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
new_random1 = np.random.randint(0, 10 , (3, 3) )
print(new_random1)
new_random2 = np.random.randint(0, 10, (3, 2))
print(new_random2)

[[6 6 8]
 [9 9 2]
 [6 0 3]]
[[3 4]
 [6 6]
 [3 6]]


In [64]:
# Perform a dot product on the two newest arrays you created
dot = new_random1.dot(new_random2)
dot

array([[ 78, 108],
       [ 87, 102],
       [ 27,  42]])

In [65]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
random_ints1 = np.random.randint(0, 10, (4, 3))
random_ints2 = np.random.randint(0, 10, (4, 3))

In [66]:
# Perform a dot product on the two newest arrays you created
random_ints1.dot(random_ints2)

ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [67]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
random_ints1.dot(random_ints2.T)

array([[  8,  39,  39,  58],
       [ 32, 128,  86, 143],
       [ 72, 121,  73,  95],
       [ 48, 120,  90, 130]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [ ]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables


In [ ]:
# Compare the two arrays with '>'


What happens when you compare the arrays with `>`?

In [ ]:
# Compare the two arrays with '>='


In [ ]:
# Find which elements of the first array are greater than 7


In [ ]:
# Which parts of each array are equal? (try using '==')


In [ ]:
# Sort one of the arrays you just created in ascending order


In [ ]:
# Sort the indexes of one of the arrays you just created


In [ ]:
# Find the index with the maximum value in one of the arrays you've created


In [ ]:
# Find the index with the minimum value in one of the arrays you've created


In [ ]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created


In [ ]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created


In [ ]:
# Create an array of normally distributed random numbers


In [ ]:
# Create an array with 10 evenly spaced numbers between 1 and 100


## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.